import { useHeartbeat } from './useHeartbeat.ts';
import { Amount, External, Pulse } from './components.tsx';
import { CreateSwitch, Switches } from './Switches.tsx';
import { Swap } from './Swap.tsx';
import { TokenTools } from './TokenTools.tsx';

export default function App() {
  const h=useHeartbeat();
  return <><a className="skip" href="#main">Skip to content</a><div className="site-shell">
    <header className="header"><a className="brand" href="#main" aria-label="Heartbeat home"><span className="brand-mark"><Pulse/></span>heartbeat<span className="brand-dot">.</span></a><div className="wallet-controls"><span className="network-pill"><span aria-hidden="true">◌</span> {h.config?.deployment.network.name??'Sepolia'} testnet</span>{h.account?<><span className="wallet-address" title={h.account}>{h.account.slice(0,6)}…{h.account.slice(-4)}</span><button className="subtle" onClick={h.disconnect} disabled={h.busy}>Disconnect</button></>:<button className="primary" onClick={()=>void h.connect()} disabled={h.connecting}>{h.connecting?'Connecting…':'Connect wallet'}<span aria-hidden="true"> ↗</span></button>}</div></header>
    <aside className="test-banner"><span className="badge">Test ETH only</span><p>This is a Sepolia test toy, not a custody or inheritance product. Use test funds only.</p></aside>
    <main id="main"><section className="hero" aria-labelledby="title"><div><p className="eyebrow">A simple signal. On chain.</p><h1 id="title">Stay in touch.<br/><em>Keep the clock alive.</em></h1><p className="intro">Set aside test ETH for someone. Check in before your timer runs out to keep control. If it lapses, your beneficiary can claim.</p></div><ol className="how-it-works"><li><span className="step">01</span><div><strong>Set your switch</strong><p>Pick a beneficiary and a period of 1–365 days.</p></div></li><li><span className="step">02</span><div><strong>Send a heartbeat</strong><p>Each check-in starts your full period again.</p></div></li><li><span className="step">03</span><div><strong>Let the timer decide</strong><p>After lapse, only the beneficiary can claim. Depositor recovery opens 365 days later.</p></div></li></ol></section>
    <div className="system-status" aria-live="polite"><span className={`status-dot ${h.verified?'verified':''}`} aria-hidden="true"/><span>{h.bootError?'Deployment verification failed':h.verified?'Deployment verified · ABI hashes, chain and contract code':'Verifying deployment…'}</span></div>
    {h.bootError&&<div className="error" role="alert"><p>{h.bootError}</p><button onClick={()=>window.location.reload()}>Retry verification</button></div>}
    {h.account&&!h.onNetwork&&<div className="wrong-network"><div><strong>Switch networks to continue</strong><p>Your wallet is on chain {h.walletChain??'unknown'}. This page uses {h.config?.deployment.network.name??'Sepolia'}.</p></div><button onClick={()=>void h.switchChain()} disabled={!h.config||h.connecting}>{h.connecting?'Switching…':`Switch to ${h.config?.deployment.network.name??'Sepolia'}`}</button></div>}
    <section className="transaction-status" aria-label="Wallet and transaction status"><p role="status">{h.status}</p>{h.error&&<p className="error" role="alert">{h.error}</p>}{h.hash&&h.config&&<External href={`${h.config.deployment.network.explorer}/tx/${h.hash}`}>View transaction {h.hash.slice(0,10)}…</External>}</section>
    {h.account&&h.onNetwork&&h.sampledAt>0&&<div className="wallet-summary"><span>Wallet <span className="address">{h.account}</span></span><span><Amount value={h.balance}/> · <Amount value={h.tokenBalance} decimals={h.decimals} unit="BEAT"/></span></div>}
    <div className="workspace"><Switches h={h}/><CreateSwitch h={h}/></div>
    <div className="lower-grid"><section className="notes" aria-labelledby="notes-title"><div className="eyebrow">Know your switch</div><h2 id="notes-title">A timer, with clear rules.</h2><details open><summary>What happens when I check in?</summary><p>A check-in resets the clock. Depositing, withdrawing, or changing the beneficiary or period also resets it. You must act before the exact lapse time.</p></details><details><summary>Can I recover a lapsed switch?</summary><p>After 365 additional days, the depositor can reclaim any unclaimed balance. The beneficiary can still claim; whichever transaction lands first closes the switch. There is no automatic payment.</p></details><details><summary>Who controls this contract?</summary><p>No owner, administrator, pause, or upgrade path exists. The contract holds only Sepolia test ETH. Never send ETH directly to its address; use a switch’s deposit control.</p></details>{h.config&&<p className="faucet-link">Need test ETH? <External href={h.config.deployment.network.faucets[0]}>Open the Sepolia faucet</External></p>}</section>{h.config&&<Swap key={`${h.account}-${h.walletChain}`} h={h}/>}</div>
    {h.config&&<section className="deployment-details" aria-label="Deployment details"><details><summary>Deployment details & token controls</summary><div className="deployment-grid"><div><h2>Verify the deployment</h2><dl className="facts">{h.config.contracts.map(c=><div key={c.name}><dt>{c.name}</dt><dd><External href={`${h.config!.deployment.network.explorer}/address/${c.address}`}>{c.address}</External></dd><dd><a href={`./${c.abiPath}`}>View {c.name} ABI</a></dd></div>)}<dt>Source commit</dt><dd className="address">{h.config.deployment.sourceCommit}</dd><dt>Attestation hash</dt><dd className="address">{h.config.deployment.attestationHash}</dd><dt>Public RPCs</dt><dd>{h.config.deployment.network.rpcUrls.map(url=><div key={url} className="address">{url}</div>)}</dd></dl><a href="./imd-deployment.json">View deployment manifest</a></div><TokenTools key={`${h.account}-${h.walletChain}`} h={h}/></div></details></section>}
    </main><footer><a className="brand small-brand" href="#main"><Pulse/> heartbeat.</a><span>Built for small experiments. Sepolia only.</span><span className="footer-label">DeadMansSwitch / 01</span></footer>
  </div></>;
}
